[package]
name = "calrs"
version = "0.1.0"
authors = ["Quang Le <iamquang95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
num-traits = "0.2"
ansi_term = "0.12.1"